common: &default_settings
  license_key: 'dfd10675e3ce84455e9092ce7347b1a42af2c7bb'
  app_name: 'Up&Sell.Me'
  monitor_mode: true
  developer_mode: false
  log_level: info
  browser_monitoring:
      auto_instrument: true
  audit_log:
    enabled: false
  capture_params: true
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"
  sidekiq:
    capture_params: true


development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: My Application (Staging)
